<?php 
$this->load->library('mpdf');
// $mpdf = new mPDF('utf-8', 'A4');
ini_set('max_execution_time', '-1');
ini_set("memory_size", "1024M");
//ini_set("memory_limit","1024M");
ini_set('memory_limit', '-1');

$mpdf = new mPDF();

if($report_type == 2){
	$i = 0;
	// $top = '<img src='.base_url('img/tz.png').' height = "20%" width = "90%">';
	$top .= '<center>';
	$top .= '<h2> '.$Final_report_title.' Report </h2>'; 
	$top .= '<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp;&nbsp; Summarized by Month &nbsp;&nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' &nbsp;&nbsp;&nbsp; Generated On: '.date("Y-m-d").' </p/>';
	$top .= '<hr/>';
	$top .= '</center>';
	$top .= '<table border="1" style="text-align: center;">';
	$top .= '<tr style="background-color: #f0f2ff;">';
		$top .= '<th></th>';
		$top .= '<th>Facility</th>';
		$top .= '<th>Tests Done</th>';
		$top .= '<th>Month</th>';
	$top .= '</tr>';
					
		foreach ($res as $key => $value) {
			$i++;				
			$body .=	'<tr>';
			$body .=	'<td> '.$i.' </td>';
			$body .=	'<td>'.$value["facility_name"].'</td>';
			$body .=	'<td>'.$value["tests_done"].'</td>';
			$body .=	'<td>'.date('F', mktime(0, 0, 0, $value["month"], 10)).'</td>';
			$body .=	'</tr>';
		}
		
						
		$bottom = '</table>
		<hr/>
		';
		
		$final_report = $top.$body.$bottom;
}else if($report_type == 1){

	$i = 0;
	// $top = '<img src='.base_url('img/tz.png').' height = "20%" width = "90%">';
	$top .= '<h2> '.$Final_report_title.' Report </h2>'; 
	$top .= '<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' &nbsp;&nbsp;&nbsp; Generated On: '.date("Y-m-d").' </p/>';	 
	$top .= '<hr/>';
	$top .= '<table border="1" style="text-align: center;">';
	$top .=	'<tr style="background-color: #f0f2ff;">';
		$top .= '<th></th>';
		$top .= '<th>Facility</th>';
		$top .= '<th>PIMA Device</th>';
		$top .= '<th>Sample Code</th>';					
		$top .= '<th> Error Type</th>';
		$top .= '<th> Error Description </th>';
		$top .= '<th> Device Operator  </th>';
		$top .= '<th> Date of Result </th>';
	$top .= '</tr>';
				
	foreach ($res as $key => $value) {
			$i++;				
			$body .= '<tr>';
				$body .= '<td> '.$i.' </td>';
				$body .= '<td>'.$value["facility_name"].'</td>';
				$body .= '<td>'.$value["equipment_serial_number"].'</td>';
				$body .= '<td>'.$value["sample_code"].'</td>';
				$body .= '<td>'.$value["error_type_description"].'	</td>';
				$body .= '<td>'.$value["error_detail"].' </td>';
				$body .= '<td>'.$value["operator"].'</td>';
				$body .= '<td>'.$value["result_date"].'</td>';
			$body .= '</tr>';
		}
	$bottom = '</table>
	<hr/>
	';
	
	
	$final_report = $top.$body.$bottom;
}else if ($report_type == 4){

	$i = 0;
	// $top = '<img src='.base_url('img/tz.png').' height = "20%" width = "90%">';
	$top .= '<center>';
	$top .=	'<h2> '.$Final_report_title.' Report </h2>'; 
	$top .= '<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' &nbsp;&nbsp;&nbsp; Generated On: '.date("Y-m-d").' </p/>';
	$top .= '<table border="1" style="text-align: center;">';
	$top .= '<tr style="background-color: #f0f2ff;">';
		$top .= '<th></th>';
		$top .= '<th>Facility</th>';
		$top .= '<th>PIMA Device</th>';
		$top .= '<th>Sample Code</th>';
		$top .= '<th>CD4 Count (cells/mm)</th>';
		$top .= '<th>SUCCESSFUL TESTS</th>';
		$top .= '<th> Device Operator  </th>';
		$top .= '<th> Date of Result </th>';
	$top .= '</tr>';
										
	foreach ($res as $key => $value) {
			$i++;				
			$body .=	'<tr>';
				$body .= 	'<td> '.$i.' </td>';
				$body .= 	'<td>'.$value["facility_name"].'</td>';
				$body .= 	'<td>'.$value["equipment_serial_number"].'</td>';
				$body .= 	'<td>'.$value["sample_code"].'</td>';
				$body .= 	'<td>'.$value["cd4_count"].'	</td>';
				$body .= 	'<td>'.$value["validity"].'</td>';
				$body .= 	'<td>'.$value["operator"].'</td>';
				$body .=	'<td>'.$value["result_date"].'</td>';
			$body . 	'</tr>';
		}
	$bottom = '</table>
	<hr/>
	';
	
	$final_report = $top.$body.$bottom;	
}else if($report_type == 3){	
	$start    = new DateTime($date_from);
	$start->modify('first day of this month');
	$end      = new DateTime($date_to);
	$end->modify('first day of next month');
	$interval = DateInterval::createFromDateString('1 month');
	$period   = new DatePeriod($start, $interval, $end);


	
	$top =	'<h2> Tests Done '.$Final_report_title.' Report </h2>'; 
	$top .= '<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp; Summarized by Month. &nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' <br> Generated On: '.date("Y-m-d").' </p/>';
	$top .= '<hr/>';
	$top .= '<table border = "1"; style="text-align: center;");>';
	$top .= '<tr style="background-color: #f0f2ff;" >';
	$top .= "<th></th>";
	$top .= "<th>Facility name</th>";
	
	foreach ($period as $dt) {
		$top .= "<th>". $dt->format("F")."</th>" ;//draw the months at the top
		
		if($dt->format("F") == "January"){
			$months_selected [0] = "January";
		}
		if($dt->format("F") == "February"){
			$months_selected [1] = "February";
		}
		if($dt->format("F") == "March"){
			$months_selected [2] = "March";
		}
		if($dt->format("F") == "April"){
			$months_selected [3] = "April";
		}
		if($dt->format("F") == "May"){
			$months_selected [4] = "May";
		}
		if($dt->format("F") == "June"){
			$months_selected [5] = "June";
		}
		if($dt->format("F") == "July"){
			$months_selected [6] = "July";
		}
		if($dt->format("F") == "August"){
			$months_selected [7] = "August";
		}
		if($dt->format("F") == "September"){
			$months_selected [8] = "September";
		}
		if($dt->format("F") == "October"){
			$months_selected [9] = "October";
		}
		if($dt->format("F") == "November"){
			$months_selected [10] = "November";
		}
		if($dt->format("F") == "December"){
			$months_selected [11] = "December";
		}
	}		
	$top.="</tr>";
	
	
	$i = 0;
	foreach ($res as $key => $value) {
		$body .= "<tr>";
		$i++;
		$body .= "<td>".$i."</td>";
		$body .= "<td>".$value["facility_name"]."</td>";
			
			if($months_selected[0] == "January"){
				$body .= "<td>".$value["jan_result"]."</td>";
			}			
			if($months_selected[1] == "February"){
				$body .= "<td>".$value["feb_result"]."</td>";
			}
			if($months_selected[2] == "March"){
				$body .= "<td>".$value["mar_result"]."</td>";
			}
			if($months_selected[3] == "April"){
				$body .= "<td>".$value["apr_result"]."</td>";
			}
			if($months_selected[4] == "May"){
				$body .= "<td>".$value["may_result"]."</td>";
			}
			if($months_selected[5] == "June"){
				$body .= "<td>".$value["jun_result"]."</td>";
			}
			if($months_selected[6] == "July"){
				$body .= "<td>".$value["jul_result"]."</td>";
			}
			if($months_selected[7] == "August"){
				$body .= "<td>".$value["aug_result"]."</td>";
			}
			if($months_selected[8] == "September"){
				$body .= "<td>".$value["sept_result"]."</td>";
			}
			if($months_selected[9] == "October"){
				$body .= "<td>".$value["oct_result"]."</td>";
			}
			if($months_selected[10] == "November"){
				$body .= "<td>".$value["nov_result"]."</td>";				
			}
			if($months_selected[11] == "December"){
				$body .= "<td>".$value["dec_result"]."</td>";
			}
		$body .= "</tr>";
	}
	$bottom = "</table>
	<hr/>
	";
	

	$final_report =  $top.$body.$bottom;
}
	$t=time();
	$timestamp = (date("m-d-y_G.i.s",$t));

	$mpdf->WriteHTML($final_report);
	//$file_name = $this->config->item('server_root').'downloads/poc_'.$Final_report_title.'_'.$timestamp.'.pdf';
	$mpdf->Output();
	// $mpdf->Output(I);
	//redirect($this->config->item('server_root').$controller, 'refresh');
	exit;	
?>









