<?php 
$this->load->library('mpdf');
// $mpdf = new mPDF('utf-8', 'A4');

$mpdf = new mPDF('c');
$mpdf->setDisplayMode('fullpage');

ini_set('max_execution_time', -1);
ini_set("memory_size", "500M");
ini_set("memory_limit","500M");

//$mpdf->packTableData = true;


// if(empty($res)){
	// echo "no data";
	// print_r("Result ". $res);
	// die;
// }else{
	// echo "data exists";
// 	
// }

// $final_report = 
// '
// <html>
// <head></head>
	// <body>
		// <center>
			// <img width="100%" height="20%" src="http://127.0.0.1/cd4/img/tz.png">
			// <h3 >Title</h3>
			// <h6 >Date</h6>
			// <table border="1" style="background-color:"#FFBBFF"; position: absolute; left: 710.353px; top: 66.9167px; font-size: 15px; font-family: sans-serif; transform: rotate(0deg) scale(1.04216, 1); transform-origin: 0% 0% 0px;" data-font-name="Helvetica" data-angle="0" >
				// <tbody>
				// <tr>
					// <td></td>
					// <td>Facility</td>
					// <td>PIMA Device</td>
					// <td>Sample Code</td>
					// <td>CD4 Count (cells/mm) </td>
					// <td> Successful Tests </td>
					// <td> Device Operator </td>
					// <td> Date of Result </td>
				// </tr>
				// <tr>
					// <td>1</td>
					// <td>2</td>
					// <td>3</td>
					// <td>4</td>
					// <td>5</td>
					// <td>6</td>
					// <td>7</td>
					// <td>8</td>
				// </tr>
				// </tbody>
			// </table>
		// </center>
		// <hr/>
		// END OF PDF
	// </body>
// </html>
// ';
// 
	// $mpdf->WriteHTML($final_report);
	// $report_name = "Test";
	// $file_name = $this->config->item('server_root').'downloads/'.$title.'.pdf';
	// $mpdf->Output($file_name,I);
	// exit;
	// die;


if($report_type == 2){
	$i = 0;
	$top = '
		<img src='.base_url('img/tz.png').' height = "20%" width = "90%">
		<center>
			<h2> '.$Final_report_title.' Report </h2> 
			<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp;&nbsp; Summarized by Month &nbsp;&nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' &nbsp;&nbsp;&nbsp; Generated On: '.date("Y-m-d").' </p/>
			<hr/>
		</center>
			<table border="1" background-color="#FFBBFF">
				<tr>
					<th></th>
					<th>Facility</th>
					<th> No. of Tests  </th>
					<th> Month </th>
				<tr>';

		foreach ($res as $key => $value) {
			$i++;				
			$body .=	'<tr>';
			$body .=	'<td> '.$i.' </td>';
			$body .=	'<td>'.$value["facility_name"].'</td>';
			$body .=	'<td>'.$value["tests_done"].'</td>';
			$body .=	'<td>'.date('F', mktime(0, 0, 0, $value["month"], 10)).'</td>';
			$body .=	'</tr>';
		}	
				
		$bottom = '</table>
		';
		
		$final_report = $top.$body.$bottom;
			
}else if($report_type == 1){

	$i = 0;
	$top = '
		<img src='.base_url('img/tz.png').' height = "20%" width = "90%">
				<h2> '.$Final_report_title.' Report </h2> 
				<p>Date: '.$date_from.' to '.$date_to.' &nbsp;&nbsp;&nbsp; Generated By: '.$this->session->userdata("name").' &nbsp;&nbsp;&nbsp; Generated On: '.date("Y-m-d").' </p/>	 
			<hr/>
			<table border="1" background-color="#FFBBFF">
				<tr>
					<th></th>
					<th>Facility</th>
					<th>PIMA Device</th>
					<th>Sample Code</th>					
					<th> Error Type</th>
					<th> Error Description </th>
					<th> Device Operator  </th>
					<th> Date of Result </th>
				<tr>';
				
	foreach ($res as $key => $value) {
			$i++;				
			$body .=	'<tr>
				<td> '.$i.' </td>
				<td>'.$value["facility_name"].'</td>
				<td>'.$value["equipment_serial_number"].'</td>
				<td>'.$value["sample_code"].'</td>
				<td>'.$value["error_type_description"].'	</td>
				<td>'.$value["error_detail"].' </td>
				<td>'.$value["operator"].'</td>
				<td>'.$value["result_date"].'</td>
			</tr>';
		}
	$bottom = '</table>
	';
	
	
	$final_report = $top.$body.$bottom;
}else {

	$i = 0;
	$top = '
		<center>
			<img src='.base_url('img/tz.png').' height = "20%" width = "90%">
			<center>
				<h2>Area: '.$criteria.' ,'.$name.'</h2>
				<p>Date '.$date_from.' - '.$date_to.' </p>
			</center>
			<table border="1" background-color="#FFBBFF">
				<tr>
					<th></th>
					<th>Facility</th>
					<th>PIMA Device</th>
					<th>Sample Code</th>
					<th>CD4 Count (cells/mm)</th>
					<th>SUCCESSFUL TESTS</th>					
					<th> Device Operator  </th>
					<th> Date of Result </th>
				<tr>';
				
	foreach ($res as $key => $value) {
			$i++;				
			$body .=	'<tr>
				<td> '.$i.' </td>
				<td>'.$value["facility_name"].'</td>
				<td>'.$value["equipment_serial_number"].'</td>
				<td>'.$value["sample_code"].'</td>
				<td>'.$value["cd4_count"].'	</td>
				<td>'.$value["validity"].'</td>
				<td>'.$value["operator"].'</td>
				<td>'.$value["result_date"].'</td>
			</tr>';
		}


	$bottom = '</table>
		</center>
	';
	
	$final_report = $top.$body.$bottom;
}
	$t=time();
	$timestamp = (date("m-d-y_G.i.s",$t));

	$mpdf->WriteHTML($final_report);
	$report_name = "Test";
	$file_name = $this->config->item('server_root').'downloads/poc_'.$Final_report_title.'_'.$timestamp.'.pdf';
	$mpdf->Output($file_name,F);
	redirect($this->config->item('server_root').$controller, 'refresh');
	exit;	
?>









